### ISSUE TITLE
Doc mistake for integratePolynomialOnSimplex non Fraction version

### ISSUE THREAD

**Issue by LhucHET** [stla/PySimplicialCubature#1]
The integral of given polynomial over 
v1 = [1.0, 1.0, 1.0] 
v2 = [2.0, 2.0, 3.0] 
v3 = [3.0, 4.0, 5.0] 
v4 = [3.0, 2.0, 1.0]
is 1387/42, or 33.023809523809526, not the given value of -0.253571428571429.
Change either domain or answer to fix?

**Comment by stla** [comment]
You are right. Thank you for the report.
